env:
  global:
    - CC_TEST_REPORTER_ID=901d3045718f66236a651e6fb24639a8d66ff4e6f631a76fcee254136b5ffe8b

language: python

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9-dev"
  allow_failures:
    - python: "3.9-dev"

install:
  - pip install pytest
  - pip install responses
  - pip install pytest-cov
  - pip install coveralls
  - pip install requests
  - pip install pyjwt
  - pip install uuid

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest --cov=tests/

after_success:
  - coveralls
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
